CREATE DATABASE `db_slim`;

CREATE TABLE `tbl_login` (`id` INT NULL );

ALTER TABLE `tbl_login`
	ADD COLUMN `firstname` VARCHAR(50) NULL DEFAULT NULL AFTER `id`,
	ADD COLUMN `lastname` VARCHAR(50) NULL DEFAULT NULL AFTER `firstname`,
	ADD COLUMN `username` VARCHAR(50) NULL DEFAULT NULL AFTER `lastname`,
	ADD COLUMN `password` VARCHAR(100) NULL DEFAULT NULL AFTER `username`,
	ADD COLUMN `token` VARCHAR(200) NULL AFTER `password`;	

CREATE TABLE `tbl_leaves` (
	`id` INT NULL,
	`user_id` INT NULL,
	`leave_date` DATETIME NULL,
	`reason` VARCHAR(50) NULL,
	`created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;